config:
  modules:
    http_4xx:
      prober: http
      timeout: 5s
      http:
        method: GET
        valid_status_codes: [401]
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"
serviceMonitor:
  enabled: true
  defaults:
    labels:
      release: prometheus
  targets:
    - name: google.com
      url: https://google.com
    - name: honeybunny.no
      url: wordpress-service.helloworld.svc.cluster.local:80
    - name: mongo.honeybunny.no
      url: mongo-express-service.mongo.svc.cluster.local:8081
      module: http_4xx
