apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU= #mongo-root-username - this name is up to me
    mongo-root-password: cGFzc3dvcmQ= #mongo-root-password - this name is up to me

    #values must be base64 encoded - simply type in console echo -n 'username' |base64
    #decode echo "your_base64_string_here" | base64 -d
