apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
namespace: helloworld
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
